# Generated by Django 6.0.6 on 2026-06-27 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_dailyclassreview_timetable_entry_attendance'),
        ('accounts', '0005_faculty'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_growth_rate', models.FloatField(default=0.0)),
                ('department_count', models.IntegerField(default=0)),
                ('branch_count', models.IntegerField(default=0)),
                ('section_count', models.IntegerField(default=0)),
                ('semester_count', models.IntegerField(default=0)),
                ('student_count', models.IntegerField(default=0)),
                ('faculty_count', models.IntegerField(default=0)),
                ('total_storage_used_bytes', models.BigIntegerField(default=0)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Admin Analytics Records',
            },
        ),
        migrations.CreateModel(
            name='AIAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_generated', models.IntegerField(default=0)),
                ('revision_notes_generated', models.IntegerField(default=0)),
                ('topics_processed', models.IntegerField(default=0)),
                ('knowledge_base_size_bytes', models.BigIntegerField(default=0)),
                ('embedding_count', models.IntegerField(default=0)),
                ('ai_accuracy', models.FloatField(default=100.0)),
                ('avg_generation_time', models.FloatField(default=0.0)),
                ('prompt_performance_score', models.FloatField(default=100.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'AI Analytics Records',
            },
        ),
        migrations.CreateModel(
            name='APIHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=255)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('success_rate', models.FloatField(default=100.0)),
                ('failure_rate', models.FloatField(default=0.0)),
                ('auth_errors_count', models.IntegerField(default=0)),
                ('validation_errors_count', models.IntegerField(default=0)),
                ('traffic_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'API Health Records',
            },
        ),
        migrations.CreateModel(
            name='DatabaseHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connections_count', models.IntegerField(default=0)),
                ('slow_queries_count', models.IntegerField(default=0)),
                ('cache_hit_ratio', models.FloatField(default=100.0)),
                ('table_sizes', models.JSONField(default=dict)),
                ('index_usage_stats', models.JSONField(default=dict)),
                ('migration_status', models.CharField(default='UP_TO_DATE', max_length=100)),
                ('suggestions', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Database Health Records',
            },
        ),
        migrations.CreateModel(
            name='StorageHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket_name', models.CharField(max_length=150)),
                ('storage_size_bytes', models.BigIntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('broken_urls_count', models.IntegerField(default=0)),
                ('upload_failures_count', models.IntegerField(default=0)),
                ('download_speed_kbps', models.FloatField(default=0.0)),
                ('duplicate_files_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Storage Health Records',
            },
        ),
        migrations.CreateModel(
            name='SystemHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_status', models.CharField(default='HEALTHY', max_length=50)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('memory_usage', models.FloatField(default=0.0)),
                ('active_connections', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'System Health Records',
            },
        ),
        migrations.CreateModel(
            name='AgentHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='RUNNING', max_length=50)),
                ('avg_response_time', models.FloatField(default=0.0)),
                ('avg_execution_time', models.FloatField(default=0.0)),
                ('error_count', models.IntegerField(default=0)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_executed_at', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_stats', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Agent Health Telemetry',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('alert_type', models.CharField(choices=[('SYSTEM', 'System'), ('DATABASE', 'Database'), ('STORAGE', 'Storage'), ('API', 'API'), ('ACADEMIC', 'Academic'), ('CR', 'CR')], default='SYSTEM', max_length=50)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='academics.section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='CRAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending_join_requests', models.IntegerField(default=0)),
                ('daily_reviews_submitted', models.IntegerField(default=0)),
                ('assignments_created', models.IntegerField(default=0)),
                ('announcements_posted', models.IntegerField(default=0)),
                ('avg_review_quality', models.FloatField(default=0.0)),
                ('late_reviews_count', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.cr')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cr_analytics', to='academics.section')),
            ],
            options={
                'verbose_name_plural': 'CR Analytics Records',
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('CR', 'Class Representative'), ('SYSTEM', 'System'), ('DATABASE', 'Database')], default='ACADEMIC', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='academics.section')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='accounts.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard_load_time', models.FloatField(default=0.0)),
                ('assignment_completion_rate', models.FloatField(default=0.0)),
                ('ai_assignment_accuracy', models.FloatField(default=0.0)),
                ('daily_usage_minutes', models.FloatField(default=0.0)),
                ('activity_score', models.FloatField(default=100.0)),
                ('experience_score', models.IntegerField(default=100)),
                ('weak_topics', models.JSONField(default=list)),
                ('progress_status', models.CharField(choices=[('AT_RISK', 'At Risk'), ('ON_TRACK', 'On Track'), ('AHEAD', 'Ahead')], default='ON_TRACK', max_length=50)),
                ('personalized_recommendations', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='accounts.student')),
            ],
            options={
                'verbose_name_plural': 'Student Analytics Records',
            },
        ),
    ]
