# Generated by Django 6.0.6 on 2026-06-27 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_adminanalytics_aianalytics_apihealth_databasehealth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenttask',
            name='approval_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agenttask',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_type',
            field=models.CharField(choices=[('ORCHESTRATOR', 'Orchestrator Agent'), ('PROJECT_MANAGER', 'Project Manager'), ('DATABASE_ARCHITECT', 'Database Architect'), ('BACKEND_API', 'Backend API'), ('AUTHENTICATION', 'Authentication'), ('STORAGE', 'Storage'), ('AI_LEARNING', 'AI Learning Agent'), ('TESTING', 'Testing Agent'), ('DOCUMENTATION', 'Documentation Agent'), ('REVIEW', 'Review Agent'), ('MONITORING', 'Monitoring & Intelligence Agent')], default='PROJECT_MANAGER', max_length=50),
        ),
        migrations.AlterField(
            model_name='agenttask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('AWAITING_APPROVAL', 'Awaiting Approval')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='agents.agentexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AgentMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=255)),
                ('metric_value', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='agents.agent')),
            ],
        ),
        migrations.CreateModel(
            name='TaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_data', models.TextField(blank=True)),
                ('execution_time', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('status', models.CharField(default='SUCCESS', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='agents.agenttask')),
            ],
        ),
        migrations.CreateModel(
            name='AgentCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='agents.agent')),
            ],
            options={
                'verbose_name_plural': 'Agent Capabilities',
                'unique_together': {('agent', 'capability_name')},
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_tasks', to='agents.agenttask')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='agents.agenttask')),
            ],
            options={
                'verbose_name_plural': 'Task Dependencies',
                'unique_together': {('task', 'depends_on')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=150)),
                ('input_mapping', models.JSONField(default=dict, help_text='Maps previous outputs to inputs')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped'), ('AWAITING_APPROVAL', 'Awaiting Approval')], default='PENDING', max_length=30)),
                ('depends_on_steps', models.JSONField(default=list, help_text='List of step numbers this step depends on')),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('timeout_seconds', models.IntegerField(default=60)),
                ('is_critical', models.BooleanField(default=True, help_text='If true, step failure fails the entire workflow')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='steps', to='agents.agent')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_list', to='agents.agentworkflow')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('workflow', 'step_number')},
            },
        ),
    ]
