# Generated by Django 6.0.6 on 2026-06-22 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_dailyclassreview_semestersubject_and_more'),
        ('accounts', '0003_data_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_progress', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('completed_subjects', models.IntegerField(default=0)),
                ('total_subjects', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_progress', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SemesterReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('performance_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('assignments_completed', models.IntegerField(default=0)),
                ('ai_assignments_completed', models.IntegerField(default=0)),
                ('strengths', models.TextField(blank=True)),
                ('weak_subjects', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reports', to='academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_reports', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='SubjectProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('ai_assignments_completed', models.IntegerField(default=0)),
                ('total_ai_assignments', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('semester_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='academics.semestersubject')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_progress', to='accounts.student')),
            ],
            options={
                'unique_together': {('student', 'semester_subject')},
            },
        ),
    ]
