"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gx)5wyrfnv&aircwcc8^mql5cahy7lgd9!)mg*ak#e+jf3hdug'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'storages',
    'corsheaders',

    'accounts',
    'colleges',
    'academics',
    'resources',
    'assignments',
    'announcements',
    'agents',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": config("DB_NAME"),
        "USER": config("DB_USER"),
        "PASSWORD": config("DB_PASSWORD"),
        "HOST": config("DB_HOST"),
        "PORT": config("DB_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.permissions.JWTAuthentication',
    ],
    'EXCEPTION_HANDLER': 'accounts.utils.custom_exception_handler',
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": config("SUPABASE_STORAGE_ACCESS_KEY"),
            "secret_key": config("SUPABASE_STORAGE_SECRET_KEY"),
            "bucket_name": config("SUPABASE_STORAGE_BUCKET"),
            "endpoint_url": config("SUPABASE_STORAGE_ENDPOINT"),
            "region_name": config("SUPABASE_STORAGE_REGION"),
            "default_acl": None,
            "querystring_auth": False,
            "file_overwrite": False,
        },
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = '/media/'

AUTH_USER_MODEL = 'accounts.User'

JAZZMIN_SETTINGS = {
    "site_title": "QISHub Admin",
    "site_header": "QISHub",
    "site_brand": "QISHub Academic OS",
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to QISHub Academic Operating System Admin",
    "copyright": "QISHub Ltd",
    "search_model": ["accounts.Student"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home",  "url": "admin:index", "permissions": ["auth.view_user"]},
        {"model": "accounts.Student"},
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "auth": "fas fa-users-cog",
        "accounts.user": "fas fa-user-shield",
        "accounts.student": "fas fa-user-graduate",
        "accounts.cr": "fas fa-user-tie",
        "accounts.crassignment": "fas fa-id-badge",
        "accounts.semesterenrollment": "fas fa-user-check",
        "accounts.joinsemesterrequest": "fas fa-paper-plane",
        "accounts.subjectprogress": "fas fa-chart-line",
        "accounts.semesterprogress": "fas fa-chart-bar",
        "accounts.semesterreport": "fas fa-file-invoice",
        "accounts.faculty": "fas fa-chalkboard-teacher",
        "colleges.college": "fas fa-university",
        "academics.department": "fas fa-building",
        "academics.branch": "fas fa-code-branch",
        "academics.section": "fas fa-th-large",
        "academics.semester": "fas fa-calendar-alt",
        "academics.subjectcatalog": "fas fa-book",
        "academics.semestersubject": "fas fa-book-open",
        "academics.subjectunit": "fas fa-layer-group",
        "academics.subjecttopic": "fas fa-hashtag",
        "academics.dailyclassreview": "fas fa-pencil-alt",
        "academics.semesterknowledgebase": "fas fa-brain",
        "academics.facultyassignment": "fas fa-user-tag",
        "academics.semestercalendar": "fas fa-calendar-check",
        "academics.semesterplan": "fas fa-road",
        "academics.semesterplanday": "fas fa-calendar-day",
        "academics.topicprogress": "fas fa-tasks",
        "academics.sectionsemester": "fas fa-chalkboard",
        "academics.timetable": "fas fa-table",
        "academics.timetableentry": "fas fa-clock",
        "assignments.assignment": "fas fa-clipboard-list",
        "assignments.questionbank": "fas fa-question-circle",
        "assignments.assignmentsubmission": "fas fa-clipboard-check",
        "announcements.announcement": "fas fa-bullhorn",
        "resources.storedfile": "fas fa-file-pdf",
        "resources.resourcelibrary": "fas fa-folder-open",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": True,
    "custom_css": None,
    "custom_js": None,
    "show_ui_builder": True,
    "changeform_format": "horizontal_tabs",
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark navbar-navy",
    "no_navbar_border": False,
    "navbar_link_flow": False,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "navy",
    "dark_mode_theme": "navy",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

GEMINI_API_KEY = config('GEMINI_API_KEY', default='YOUR_GEMINI_API_KEY')


