# Generated by Django 6.0.6 on 2026-06-22 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_semester_status_alter_semester_department_branch_and_more'),
        ('accounts', '0003_data_migration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyClassReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('class_date', models.DateField()),
                ('topics_covered', models.TextField()),
                ('faculty_notes', models.TextField(blank=True)),
                ('important_questions', models.TextField(blank=True)),
                ('exam_hints', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cr_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reviews', to='accounts.crassignment')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_topics', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('embedding_reference', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_entry', to='academics.dailyclassreview')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='academics.semestersubject')),
            ],
        ),
        migrations.AddField(
            model_name='dailyclassreview',
            name='semester_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_reviews', to='academics.semestersubject'),
        ),
        migrations.CreateModel(
            name='SubjectCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('credits', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='semestersubject',
            name='subject_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_subjects', to='academics.subjectcatalog'),
        ),
        migrations.AlterUniqueTogether(
            name='semestersubject',
            unique_together={('semester', 'subject_catalog')},
        ),
    ]
