# Generated by Django 6.0.6 on 2026-06-22 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_facultyassignment_semestercalendar_semesterplan_and_more'),
        ('accounts', '0005_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyassignment',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='facultyassignment',
            name='semester_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_assignments', to='academics.semestersubject'),
        ),
        migrations.AddField(
            model_name='semestercalendar',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='semesterplan',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='semesterplanday',
            name='planned_faculty',
            field=models.ManyToManyField(blank=True, to='accounts.faculty'),
        ),
        migrations.AddField(
            model_name='semesterplanday',
            name='planned_subjects',
            field=models.ManyToManyField(blank=True, to='academics.semestersubject'),
        ),
        migrations.AddField(
            model_name='semesterplanday',
            name='semester_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='academics.semesterplan'),
        ),
        migrations.AddField(
            model_name='semesterplanday',
            name='planned_topics',
            field=models.ManyToManyField(blank=True, to='academics.subjecttopic'),
        ),
        migrations.AddField(
            model_name='dailyclassreview',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='daily_reviews', to='academics.subjecttopic'),
        ),
        migrations.AddField(
            model_name='subjectunit',
            name='subject_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='academics.subjectcatalog'),
        ),
        migrations.AddField(
            model_name='subjecttopic',
            name='subject_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.subjectunit'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='semester_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='academics.semestersubject'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='subject_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='academics.subjecttopic'),
        ),
        migrations.AlterUniqueTogether(
            name='facultyassignment',
            unique_together={('faculty', 'semester_subject')},
        ),
        migrations.AlterUniqueTogether(
            name='subjectunit',
            unique_together={('subject_catalog', 'unit_number')},
        ),
        migrations.AlterUniqueTogether(
            name='topicprogress',
            unique_together={('semester_subject', 'subject_topic')},
        ),
    ]
