# Generated by Django 6.0.6 on 2026-06-22 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_facultyassignment_semestercalendar_semesterplan_and_more'),
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('bucket_name', models.CharField(max_length=100)),
                ('mime_type', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.IntegerField(default=1)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('NOTES', 'Notes'), ('PPT', 'Presentation'), ('QUESTION_BANK', 'Question Bank'), ('PREVIOUS_PAPER', 'Previous Paper'), ('SYLLABUS', 'Syllabus'), ('LAB_MANUAL', 'Lab Manual'), ('ASSIGNMENT', 'Assignment'), ('TIMETABLE', 'Timetable'), ('ACADEMIC_CALENDAR', 'Academic Calendar')], max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='academics.semestersubject')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_mappings', to='resources.storedfile')),
            ],
            options={
                'verbose_name_plural': 'Resource Library Entries',
            },
        ),
    ]
